# Generated by Django 4.1 on 2022-08-20 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nozzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('diameter', models.PositiveIntegerField()),
                ('profile', models.CharField(choices=[('Optima', 'Optima'), ('19A', '19A')], max_length=32)),
                ('profile_height', models.PositiveIntegerField()),
                ('inner_ring_type', models.CharField(choices=[('Complete st. st. inside', 'Complete st. st. inside'), ('St. st. ring inside', 'St. st. ring inside'), ('Complete steel', 'Complete steel'), ('St. st. ring and outlet', 'St. st. ring and outlet')], max_length=32)),
                ('inner_ring_thickness_propeller_zone', models.PositiveIntegerField()),
                ('inner_ring_thickness_inlet_zone', models.PositiveIntegerField()),
                ('inner_ring_thickness_outlet_zone', models.PositiveIntegerField()),
                ('ribs_quantity', models.PositiveIntegerField()),
                ('ribs_thickness', models.PositiveIntegerField()),
                ('segments_quantity', models.PositiveIntegerField()),
                ('segments_thickness', models.PositiveIntegerField()),
                ('has_headbox', models.BooleanField()),
                ('has_outlet_ring', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('order_dmcg_number', models.CharField(max_length=32)),
                ('order_client_number', models.CharField(max_length=32)),
                ('nozzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.nozzle')),
            ],
        ),
    ]
