# Generated by Django 4.1 on 2022-08-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nozzle',
            name='real_weight',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='nozzle',
            name='theoretical_weight',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
