# Generated by Django 4.1 on 2022-09-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_nozzle_real_weight_nozzle_theoretical_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='nozzle',
            name='drawing_number',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
