# Generated by Django 4.1 on 2022-09-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='order_client_number',
            new_name='offer_client_number',
        ),
    ]
