# Generated by Django 4.1 on 2022-09-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_rename_order_client_number_offer_offer_client_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='offer_client_number',
            new_name='client_inquiry_number',
        ),
    ]
