# Generated by Django 4.1 on 2022-09-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_rename_offer_client_number_offer_client_inquiry_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_client_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
