# Generated by Django 4.1 on 2022-09-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_offer_offer_client_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='offer_client_number',
        ),
    ]
