# Generated by Django 4.1 on 2022-09-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_nozzlecalculation_additionalhours'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditionalHours',
            new_name='AdditionalNozzleHours',
        ),
    ]
