# Generated by Django 4.1 on 2022-10-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0012_nozzlecalculation_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalnozzlehours',
            name='group',
            field=models.CharField(blank=True, choices=[('assembly_hours', 'Montaż'), ('welding_hours', 'Spawanie'), ('spinning_hours', 'Wyoblanie'), ('small_machining_hours', 'Obróbka lekka'), ('medium_machining_hours', 'Obróbka średnia'), ('tos_machining_hours', 'Obróbka TOS'), ('cutting_plates_hours', 'Palenie blach'), ('bending_hours', 'Gięcie blach'), ('rolling_profiles_hours', 'Walcowanie rur')], max_length=40, null=True),
        ),
    ]
