# Generated by Django 4.1 on 2022-10-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0013_additionalnozzlehours_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalnozzlehours',
            name='comment',
            field=models.TextField(max_length=200),
        ),
    ]
