# Generated by Django 4.1 on 2022-10-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0014_alter_additionalnozzlehours_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalnozzlehours',
            name='additional_hours_amount',
            field=models.PositiveIntegerField(),
        ),
    ]
