# Generated by Django 4.1 on 2022-10-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0015_alter_additionalnozzlehours_additional_hours_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='nozzlecalculation',
            name='diameter',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nozzlecalculation',
            name='drawing_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='nozzlecalculation',
            name='has_headbox',
            field=models.BooleanField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nozzlecalculation',
            name='has_outlet_ring',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nozzlecalculation',
            name='inner_ring_thickness_inlet_zone',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nozzlecalculation',
            name='inner_ring_thickness_outlet_zone',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nozzlecalculation',
            name='inner_ring_thickness_propeller_zone',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nozzlecalculation',
            name='inner_ring_type',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nozzlecalculation',
            name='profile',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nozzlecalculation',
            name='profile_height',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nozzlecalculation',
            name='real_weight',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='nozzlecalculation',
            name='ribs_quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nozzlecalculation',
            name='ribs_thickness',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nozzlecalculation',
            name='segments_quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nozzlecalculation',
            name='segments_thickness',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nozzlecalculation',
            name='theoretical_weight',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
